// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
const { defineConfig } = require("prisma/config");

module.exports = defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: process.env.DATABASE_URL,
  },
});